create_clock -period 10.000 -name clk -waveform {0.000 5.000} [get_ports clk]
create_generated_clock -name fp/clk2 -source [get_ports clk] -divide_by 5 [get_pins fp/clk2_reg/Q]
create_clock -period 50.000 -name VIRTUAL_fp/clk2 -waveform {0.000 25.000}
set_input_delay -clock [get_clocks VIRTUAL_fp/clk2] -min -add_delay 0.200 [get_ports {slide_switch[*]}]
set_input_delay -clock [get_clocks VIRTUAL_fp/clk2] -max -add_delay 0.200 [get_ports {slide_switch[*]}]
set_input_delay -clock [get_clocks clk] -min -add_delay 0.200 [get_ports rst]
set_input_delay -clock [get_clocks clk] -max -add_delay 0.200 [get_ports rst]
set_input_delay -clock [get_clocks VIRTUAL_fp/clk2] -min -add_delay 0.200 [get_ports rst]
set_input_delay -clock [get_clocks VIRTUAL_fp/clk2] -max -add_delay 0.200 [get_ports rst]


set_property PACKAGE_PIN W5 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports NSYNC]
set_property IOSTANDARD LVCMOS33 [get_ports {slide_switch[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {slide_switch[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {slide_switch[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {slide_switch[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {slide_switch[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {slide_switch[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {slide_switch[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {slide_switch[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {slide_switch[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {slide_switch[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {slide_switch[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {slide_switch[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {slide_switch[0]}]
set_property PACKAGE_PIN W15 [get_ports {slide_switch[3]}]
set_property PACKAGE_PIN V15 [get_ports {slide_switch[4]}]
set_property PACKAGE_PIN W14 [get_ports {slide_switch[5]}]
set_property PACKAGE_PIN W13 [get_ports {slide_switch[6]}]
set_property PACKAGE_PIN V2 [get_ports {slide_switch[7]}]
set_property PACKAGE_PIN V16 [get_ports {slide_switch[0]}]
set_property PACKAGE_PIN W16 [get_ports {slide_switch[1]}]
set_property PACKAGE_PIN W17 [get_ports {slide_switch[2]}]
set_property PACKAGE_PIN T3 [get_ports {slide_switch[8]}]
set_property PACKAGE_PIN T2 [get_ports {slide_switch[9]}]
set_property PACKAGE_PIN R3 [get_ports {slide_switch[10]}]
set_property PACKAGE_PIN W2 [get_ports {slide_switch[11]}]
set_property PACKAGE_PIN U1 [get_ports {slide_switch[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports rst]
set_property PACKAGE_PIN V17 [get_ports rst]
set_property PACKAGE_PIN A14 [get_ports NSYNC]
set_property PACKAGE_PIN B16 [get_ports SCLK]
set_property PACKAGE_PIN A16 [get_ports SDATA1]
set_property PACKAGE_PIN B15 [get_ports SDATA2]
set_property IOSTANDARD LVCMOS33 [get_ports SCLK]
set_property IOSTANDARD LVCMOS33 [get_ports SDATA1]
set_property IOSTANDARD LVCMOS33 [get_ports SDATA2]
